include: package:lints/recommended.yaml

analyzer:
  exclude:
    - build/**

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_constructors_in_immutables: true
    avoid_print: true
    unnecessary_breaks: true
    exhaustive_cases: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    curly_braces_in_flow_control_structures: false
